"""add tool calling fields to chat_messages

Revision ID: 68c07170dca3
Revises: 8f1c2d3e4a5b
Create Date: 2026-09-30 19:13:58.129818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c07170dca3'
down_revision: Union[str, None] = '8f1c2d3e4a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('chat_messages', sa.Column('tool_calls', sa.JSON(), nullable=True))
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('invoices', sa.Column('client_id', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('invoices', sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELED', name='invoicestatus'), nullable=False))
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('order_items', sa.Column('product_name', sa.String(), nullable=False))
    op.add_column('order_items', sa.Column('unit_price', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('created_at', sa.Date(), nullable=False))
    op.add_column('orders', sa.Column('total_amount', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('estimated_delivery_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'estimated_delivery_date')
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'created_at')
    op.drop_column('order_items', 'unit_price')
    op.drop_column('order_items', 'product_name')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_column('invoices', 'status')
    op.drop_column('invoices', 'amount')
    op.drop_column('invoices', 'client_id')
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('chat_messages', 'tool_calls')
    op.drop_column('chat_messages', 'name')
    # ### end Alembic commands ###
